language: node_js

node_js:
  - "12"

install:
  - npm install

script:
  - npx hardhat test
  - npx hardhat coverage

after_success:
  - cat coverage/lcov.info | npx coveralls
  
cache: npm

branches:
  only:
    - main